create table cars (
  ID serial,
  USER_ID integer,
  PLATE varchar(25)
  );



INSERT INTO CARS (USER_ID, PLATE) VALUES(1,'79057JN');
INSERT INTO CARS (USER_ID, PLATE) VALUES(2,'BXW4982');
INSERT INTO CARS (USER_ID, PLATE) VALUES(3,'HMK7819');
INSERT INTO CARS (USER_ID, PLATE) VALUES(4,'54886PC');
INSERT INTO CARS (USER_ID, PLATE) VALUES(5,'FJW9630');
INSERT INTO CARS (USER_ID, PLATE) VALUES(6,'9N50A');
INSERT INTO CARS (USER_ID, PLATE) VALUES(7,'HTV3090');
INSERT INTO CARS (USER_ID, PLATE) VALUES(8,'GKE2943');
INSERT INTO CARS (USER_ID, PLATE) VALUES(9,'HUU1104');
INSERT INTO CARS (USER_ID, PLATE) VALUES(10,'GPK7303');
INSERT INTO CARS (USER_ID, PLATE) VALUES(11,'HVX4692');
INSERT INTO CARS (USER_ID, PLATE) VALUES(12,'GGU3570');
INSERT INTO CARS (USER_ID, PLATE) VALUES(13,'T743762C');
INSERT INTO CARS (USER_ID, PLATE) VALUES(14,'6CV2691');
INSERT INTO CARS (USER_ID, PLATE) VALUES(1,'41939ML');
INSERT INTO CARS (USER_ID, PLATE) VALUES(2,'FLX3833');
INSERT INTO CARS (USER_ID, PLATE) VALUES(3,'66728MJ');
INSERT INTO CARS (USER_ID, PLATE) VALUES(4,'HXK1805');
INSERT INTO CARS (USER_ID, PLATE) VALUES(5,'T640617C');
INSERT INTO CARS (USER_ID, PLATE) VALUES(6,'AUE2917');
INSERT INTO CARS (USER_ID, PLATE) VALUES(7,'GUH6533');
INSERT INTO CARS (USER_ID, PLATE) VALUES(8,'DZD7113');
INSERT INTO CARS (USER_ID, PLATE) VALUES(9,'6H25J');
INSERT INTO CARS (USER_ID, PLATE) VALUES(10,'T748855C');
INSERT INTO CARS (USER_ID, PLATE) VALUES(11,'HPA2977');
INSERT INTO CARS (USER_ID, PLATE) VALUES(12,'VSH7049');
INSERT INTO CARS (USER_ID, PLATE) VALUES(13,'FZF7246');
INSERT INTO CARS (USER_ID, PLATE) VALUES(14,'HCB1448');